service: demo-simple

provider:
  name: aws
  region: us-east-1
  runtime: python3.8
  deploymentBucket:
    name: agutoli-my-test-bucket

custom:
  serverless-layers:
    dependenciesPath: requirements.txt
    packageManagerExtraArgs: '--no-color'
    compatibleRuntimes: ["python3.8"]

functions:
  hello:
    handler: handler.hello
    layers:
      - { Ref: MyLayerLambdaLayer }

plugins:
  - serverless-layers

layers:
  myLayer:
    package:
      artifact: .serverless/demo-simple.zip
